# Generated by Django 6.0 on 2025-12-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
